#ifndef CONFIG_H
#define CONFIG_H

#define NUM_ALTERNATIVAS 5
#define NUM_UNIDADES 3
#define NUM_DIFICULDADES 3
#define CASAS_POR_UNIDADE 10
#define TOTAL_CASAS (NUM_UNIDADES * CASAS_POR_UNIDADE)

#define PERGUNTAS_POR_UNIDADE 6
#define TOTAL_PERGUNTAS (NUM_UNIDADES * PERGUNTAS_POR_UNIDADE)

#define PENALIDADE_ERRO 1
#define AVANCO_CASA_ESPECIAL 2
#define RECUO_CASA_ESPECIAL 2

#endif
